proxy_cache_path /nix/nar-cache levels=1:2 keys_zone=nar-cache:4m max_size=16g inactive=60m use_temp_path=off;

server {
  listen 8080;
  server_name nar-cache;

  location / {
    proxy_cache nar-cache;
    proxy_pass http://app:8080;
    proxy_http_version 1.1;
    proxy_set_header Connection "keep-alive";
  }
}
