[[icedos.repositories]]
url = "github:icedos/apps"
fetchDependencies = false
modules = [
  "ambiled",
  "bb-launcher",
  "eden",
  "low-latency-vulkan-layer",
  "nx-optimizer",
  "prefixer",
  "reigntweak",
  "sekirofpsunlock",
  "spotube",
  "steam",
  "steam-sunshine-headless-session",
  "sunshine",
  "unshade",
]

[icedos.applications.steam.headlessSession]
output = "NULL-0"

[icedos.system]
packages = [
  "stremio-linux-shell",
]
version = "26.05"
