[[icedos.repositories]]
url = "github:icedos/apps"
fetchDependencies = false
modules = [
  "ambiled",
  "prefixer",
  "sekirofpsunlock",
  "steam",
  "steam-sunshine-headless-session",
  "sunshine",
]

[[icedos.repositories]]
url = "github:icedos/providers"
modules = [
  "jovian",
]

[icedos.applications.steam.headless-session]
colorManagement = true
hdr = true
inputInjection = true

[icedos.system]
packages = [
  "android-studio",
  "stremio-linux-shell",
]
version = "26.05"
