[[icedos.repositories]]
url = "github:icedos/apps"
fetchDependencies = false
modules = [
  "sunshine",
]

[icedos.system]
version = "26.05"

[[icedos.system.overlays.fromChannel]]
url = "github:nixos/nixpkgs/nixos-unstable-small"
packages = ["sunshine"]
