[[icedos.repositories]]
url = "github:icedos/kde"
modules = [
  "dynamic-workspaces",
  "krohnkite",
  "layout-osd",
  "move-to-desktop-follow",
  "no-titlebar",
  "plasmazones",
  "window-borders",
]

[icedos.system]
version = "26.05"
